# This is a basic workflow to help you get started with Actions

name: "docker-run"

# Controls when the action will run. 
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-cfn-templates:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Get Private Action
        id: action-get
        uses: actions/checkout@v2
        with:
          repository: V838688/Policy-as-Code
          ref: refs/heads/cfn-2.0
          persist-credentials: false
          path: ./.github/actions/Policy-as-Code
      - name: Docker CFN Step
        id: docker-cfn
        uses: ./.github/actions/Policy-as-Code
        with:
          rule-file-name: 'ruleset_migrated.guard'
          app_CI_key: 'TES'
          ms-teams-webhook: ''
          color_style: 'dark'
